version: '3.7'
services:
  liferaft:
    container_name: liferaft
    restart: on-failure
    build:
      context: .
      dockerfile: .docker/dev/Dockerfile
      args:
        - APP_ENV=local
        - USER=mage
        - UID=1000
    volumes:
      - .:/var/www
      - liferaft_nm:/var/www/node_modules
      - liferaft_vn:/var/www/vendor
    networks:
      - liferaft_services
    ports:
      - 8080:80
    environment:
      - APP_NAME=LifeRaft
      - APP_ENV=local
      - APP_KEY=
      - APP_DEBUG=true
      - APP_URL=http://localhost
      - LOG_CHANNEL=stack
      - LOG_DEPRECATIONS_CHANNEL=null
      - LOG_LEVEL=debug
      - DB_CONNECTION=mysql
      - DB_HOST=liferaft_db
      - DB_PORT=3306
      - DB_DATABASE=liferaft
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - BROADCAST_DRIVER=log
      - CACHE_DRIVER=file
      - FILESYSTEM_DRIVER=local
      - QUEUE_CONNECTION=sync
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120
    expose:
      - 80

networks:
  liferaft_services:
    external: true

volumes:
  liferaft_nm:
  liferaft_vn:
